# Make sure you list all the project template files here in the manifest.
stylesheet 'compass_bootstrap.scss', :media => 'screen, projection'
stylesheet '_accordion.scss', :media => 'screen, projection'
stylesheet '_alerts.scss', :media => 'screen, projection'
stylesheet '_breadcrumbs.scss', :media => 'screen, projection'
stylesheet '_button-groups.scss', :media => 'screen, projection'
stylesheet '_buttons.scss', :media => 'screen, projection'
stylesheet '_carousel.scss', :media => 'screen, projection'
stylesheet '_close.scss', :media => 'screen, projection'
stylesheet '_code.scss', :media => 'screen, projection'
stylesheet '_component-animations.scss', :media => 'screen, projection'
stylesheet '_dropdowns.scss', :media => 'screen, projection'
stylesheet '_forms.scss', :media => 'screen, projection'
stylesheet '_grid.scss', :media => 'screen, projection'
stylesheet '_hero-unit.scss', :media => 'screen, projection'
stylesheet '_labels.scss', :media => 'screen, projection'
stylesheet '_layouts.scss', :media => 'screen, projection'
stylesheet '_mixins.scss', :media => 'screen, projection'
stylesheet '_modals.scss', :media => 'screen, projection'
stylesheet '_navbar.scss', :media => 'screen, projection'
stylesheet '_navs.scss', :media => 'screen, projection'
stylesheet '_pager.scss', :media => 'screen, projection'
stylesheet '_pagination.scss', :media => 'screen, projection'
stylesheet '_popovers.scss', :media => 'screen, projection'
stylesheet '_progress-bars.scss', :media => 'screen, projection'
stylesheet '_reset.scss', :media => 'screen, projection'
stylesheet '_responsive.scss', :media => 'screen, projection'
stylesheet '_scaffolding.scss', :media => 'screen, projection'
stylesheet '_sprites.scss', :media => 'screen, projection'
stylesheet '_tables.scss', :media => 'screen, projection'
stylesheet '_thumbnails.scss', :media => 'screen, projection'
stylesheet '_tooltip.scss', :media => 'screen, projection'
stylesheet '_type.scss', :media => 'screen, projection'
stylesheet '_utilities.scss', :media => 'screen, projection'
stylesheet '_variables.scss', :media => 'screen, projection'
stylesheet '_wells.scss', :media => 'screen, projection'

discover :javascript

description "SCSS port of less version of twitter bootstrap"
